# Generated by Django 5.1.2 on 2024-11-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_records',
            field=models.JSONField(default=list),
        ),
    ]
